# -*- coding: utf-8 -*-
"""hyundai_parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nj8904Dr3RcooCgCkYF-3w3hN-5uKgc3
"""

import csv
import numpy as np
import pandas as pd
from google.colab import files

f = files.upload()
fname = list(f.keys())[0]

df = pd.read_csv(fname)
df.sort_values(by=['_id'])

df2 = df.drop(columns=['_id'])
df2.rename(columns={
  'category1': '대구분',
  'category2': '중구분',
  'maker': '메이커',
  'category3': '소구분',
  'standard': '규격',
  'vehicleType': '세부차종',
  'year': '차량연식',
  'mainPrice': '대표가격',
  'privatePrice': '자가용가격',
}, inplace=True)
df2.to_csv('hyundaicommercial.csv', index=False)
files.download('hyundaicommercial.csv') 
df2.head()